name: Put code in Releases
on: push
jobs: 
    release-project:
        name: Release code in releases
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps: 
            # Permet que s'utilitzi el repositori actual
            - uses: actions/checkout@v2 
            # Penjem tots els arxius als artifacs
            - name: Upload to artifacts
              uses: actions/upload-artifact@v2
              with:
                name: files
                path: |
                  ./
                  !.github/
            - name: Download from artifacts
              uses: actions/download-artifact@v2
              with:
                name: files
            - name: Compress files
              uses: thedoctor0/zip-release@0.7.1
              with:
                filename: files.zip
            - name: Create GitHub Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: Release V$ff github.run_number }}
                files: files.zip
